name: Metrics

on:
  # Actualizaciones automáticas cada hora
  schedule:
    - cron: "0 */1 * * *"

  # Permite ejecutarlo manualmente
  workflow_dispatch:

  # Ejecutarlo cuando haya push a main
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN_ERICK }}

          # Configuración principal
          user: Erickpe8
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota

          # Mejoras de estabilidad recomendadas
          retries: 3
          delay: 20
