name: Update Streak SVG

permissions:
  contents: write  

on:
  schedule:
    - cron: "0 6 * * *" # 1 AM COL
  workflow_dispatch:

jobs:
  streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.METRICS_TOKEN }} 

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install node-fetch@2

      - name: Fetch contributions using GraphQL
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: node scripts/fetch-streak.js

      - name: Generate final SVG
        run: node scripts/generate-svg.js

      - name: Commit streak.svg
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git pull --rebase
          
          git add assets/streak.svg streak-data.json
          git commit -m "Auto-update streak SVG" || echo "No changes"
          
          git push
